services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - GCP_PROJECT_ID=google-cloud-project-id
      - SETTINGS_MODULE=app.settings
      - CODECOV_TOKEN=${CODECOV_TOKEN}
      - INSIDE_CI=${INSIDE_CI}
